application: guestbook-167203
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: main.app

libraries:
- name: django
  version: "1.5"

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'
